apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  annotations:
  name: letsencrypt
spec:
  acme:
    dns01:
      providers:
      - name: aws
        route53:
          accessKeyID: <ACCESS_KEY_ID>
          region: us-west-2
          secretAccessKeySecretRef:
            key: secret-access-key
            name: route53-svc-acct-secret
    email: <EMAIL>
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    server: https://acme-v02.api.letsencrypt.org/directory