{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "akkeris.common.metaLabels" . | nindent 4 }}
  name: {{ template "akkeris.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "akkeris.serviceAccountName.akkeris" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
{{- end }}