# This is a simple example of using a config map to create a single page static site.
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "akkeris.logshuttle.labels" . | nindent 4 }}
  name: {{ template "akkeris.logshuttle.fullname" . }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}