{{- if .Values.serviceAccounts.akkeris.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "akkeris.common.metaLabels" . | nindent 4 }}
  name: {{ template "akkeris.serviceAccountName.akkeris" . }}
{{- end }}