apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: logshuttle
  name: logshuttle
  namespace: akkeris-system
spec:
  replicas: 2
  selector:
    matchLabels:
      name: logshuttle
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: logshuttle
      name: logshuttle
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: logshuttle
        image: akkeris/logshuttle:release-17
        imagePullPolicy: IfNotPresent
        name: logshuttle
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
          limits:
            cpu: "1.0"
            memory: "512Mi"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30