apiVersion: v1
data:
  AUTH_KEY: "{{ .Values.logsession.authKey }}"
  KAFKA_HOSTS: "{{ .Values.logsession.kafkaHosts }}"
  PORT: "5000"
  POSTGRES_URL: "{{ .Values.logsession.database }}"
  SYSLOG: "{{ .Values.logsession.syslog }}"
kind: ConfigMap
metadata:
  annotations:
  name: logshuttle
  namespace: akkeris-system
