apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app: sidecar-injector
    install.operator.istio.io/owning-resource: installed-state
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: default
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.6.7
    release: istio
  name: istio-sidecar-injector
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMzakNDQWNhZ0F3SUJBZ0lSQUlzWW5TRGdwVjcrRVliOVhQQ0xaZW93RFFZSktvWklodmNOQVFFTEJRQXcKR0RFV01CUUdBMVVFQ2hNTlkyeDFjM1JsY2k1c2IyTmhiREFlRncweU1EQXhNamN4TkRVMU1qTmFGdzB6TURBeApNalF4TkRVMU1qTmFNQmd4RmpBVUJnTlZCQW9URFdOc2RYTjBaWEl1Ykc5allXd3dnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRGFPRUNGbmozTVNCZTlVMU8wUzl3Ty9RY3JpRzE0aTJOTjIzSC8KZ3FVZjFsN3lBSFpCTmJqQmZsVk5Fc0xPbjhlK2VOK1ZIdlk0b0kxOWRnUStkODJtMXN5K0tZWnVzS3J6azZHaAo4N2xDb3dLYTZsTzg3VER2M1AvaUFYTkVHSnNBSWI1b3UzenNMWTV6YnVoL3QzMHJMdVVrN1RBaXc3VXp2MlprCi9nU29ZY0hoQVBUVC9BcmI3cC9VVnRRVVROcTNOM3Bralp1Ti8yTXNHREc0OFlDMlFaakNZTXRFeHBPb1FJZ2MKdGVodlNLZk80QmFVNzdhb0tjRTVlbzBpbFdTUDQ2UVg5M1BDKzUrVll5MFoxVWwxNjJIa3gvTjlhc0luUTZsSQo2SjVqUHdKbXJ3MTZsNGU5UG5OUUZjN0MvYWh4dThxckZBM2xNbWsySWJmL0hlVC9BZ01CQUFHakl6QWhNQTRHCkExVWREd0VCL3dRRUF3SUNCREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUIKQVFBY09DTlQyVmtvYjNBdnpWY2M0ZGJ4UTM5T2xZSzFsOHkrdFJxaEZxQmpUM3JIL3grYVBCMnZyRlJ1ajlpNgpuOFY0MWxVZ0FxT3lrN2pGcE9KWWMyTWk5aHY5U1J6TlZvOTN2QUUvUEFJTnBubVowTFNsdFA5UkwvNkJrMkErCnloTzFNSU5hM2wwK1JaMm9kQVp0L3U4ZHNvYWJIeDJoa2xMTXc3T2pTRFhjdGtISDB0TDVsOVZrOTFxcld6ZTkKRjR6dVA4dGdCV0ZpZnByZ29ndkdsajZGUDNsUzdTMmhsd2ZBZkdsaldnd0Q2TmZHTTI4aldXZXU1a3ppUXFWcgpqQUZud3N2K1NiK0k2dG1CaFUzemRVWXhpRzBzNzVBVjg2UHp6RGtDWWUvZFZtQWxqYTBIbGxKU0syZmZSU2dYCkxUYmtuU3ByTUhmUHNOTVV0N2hEK0p3QgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: istiod
      namespace: istio-system
      path: /inject
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: sidecar-injector.istio.io
  namespaceSelector:
    matchExpressions:
    - key: name
      operator: NotIn
      values:
      - istio-system
    - key: istio-injection
      operator: NotIn
      values:
      - disabled
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
