apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  namespace: akkeris-system
  name: region-api-certificate
  annotations:
    "app.kubernetes.io/name": "akkeris"
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/version": "{{ .Chart.AppVersion }}"
    "app.kubernetes.io/component": "ingress"
spec:
  secretName: region-api-certificate
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: {{.Values.name}}api.{{.Values.domain}}
  dnsNames:
  - {{.Values.name}}api.{{.Values.domain}}
  - {{.Values.name}}-api.{{.Values.domain}}
  acme:
    config:
    - dns01:
        provider: {{.Values.clusterissuer}}
      domains:
      - {{.Values.name}}api.{{.Values.domain}}
      - {{.Values.name}}-api.{{.Values.domain}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    "app.kubernetes.io/name": "akkeris"
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/version": "{{ .Chart.AppVersion }}"
    "app.kubernetes.io/component": "ingress"
    kubernetes.io/ingress.class: nginx-internal
  generation: 1
  name: region-api
  namespace: akkeris-system
spec:
  rules:
  - host: {{.Values.name}}api.{{.Values.domain}}
    http:
      paths:
      - backend:
          serviceName: region-api
          servicePort: 80
  - host: {{.Values.name}}-api.{{.Values.domain}}
    http:
      paths:
      - backend:
          serviceName: region-api
          servicePort: 80
  tls:
  - hosts:
    - {{.Values.name}}api.{{.Values.domain}}
    - {{.Values.name}}-api.{{.Values.domain}}
    secretName: region-api-certificate
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    "app.kubernetes.io/name": "akkeris"
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/version": "{{ .Chart.AppVersion }}"
    "app.kubernetes.io/component": "ingress"
  name: logsession-akkeris-system
  namespace: sites-system
spec:
  gateways:
  - apps-public
  hosts:
  - logsession.{{.Values.name}}.{{.Values.domain}}
  http:
  - route:
    - destination:
        host: logsession.akkeris-system.svc.cluster.local
        port:
          number: 80