serviceAccount:
  enabled: true
# This is used to generate minimal demo mode. It is included from demo and demo-auth values.
# It is shipped with the release, used for bookinfo or quick installation of istio.
# Includes components used in the demo, defaults to alpha3 rules.
# Note: please only put common configuration for the demo profiles here.
global:
  controlPlaneSecurityEnabled: false
  mtls:
    # Default setting for service-to-service mtls. Can be set explicitly using
    # destination rules or service annotations.
    enabled: false
  proxy:
    accessLogFile: "/dev/stdout"
    resources:
      requests:
        cpu: 10m
        memory: 40Mi

  disablePolicyChecks: false

  sidecarInjectorWebhook:
    enabled: true
    # If true, webhook or istioctl injector will rewrite PodSpec for liveness
    # health check to redirect request to sidecar. This makes liveness check work
    # even when mTLS is enabled.
    rewriteAppHTTPProbe: false

pilot:
  traceSampling: 100.0

galley:
  enabled: true

mixer:
  policy:
    enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi

  telemetry:
    enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
 
  adapters:
    prometheus:
      enabled: true
      metricsExpiryDuration: 10m
 
grafana:
  enabled: true

tracing:
  enabled: true

kiali:
  enabled: true

gateways:
  istio-ingressgateway:
    enabled: false
  sites-public-ingressgateway:
    type: LoadBalancer
    labels:
      app: sites-public-ingressgateway
      istio: sites-public-ingressgateway
    enabled: true
    ports:
      - port: 80
        targetPort: 80
        name: http2
      - port: 443
        targetPort: 443
        name: https
      - port: 15020
        name: http-status
        targetPort: 15020
      - port: 15000
        name: http-proxy
        targetPort: 15000
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
    sds:
      enabled: true
      image: node-agent-k8s
  sites-private-ingressgateway:
    type: LoadBalancer
    labels:
      app: sites-private-ingressgateway
      istio: sites-private-ingressgateway
    enabled: true
    ports:
      - port: 80
        targetPort: 80
        name: http2
      - port: 443
        targetPort: 443
        name: https
      - port: 15020
        name: http-status
        targetPort: 15020
      - port: 15000
        name: http-proxy
        targetPort: 15000
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
    sds:
      enabled: true
      image: node-agent-k8s
  apps-private-ingressgateway:
    type: LoadBalancer
    labels:
      app: apps-private-ingressgateway
      istio: apps-private-ingressgateway
    enabled: true
    ports:
      - port: 80
        name: http2
        targetPort: 80
      - port: 443
        targetPort: 443
        name: https
      - port: 15020
        name: http-status
        targetPort: 15020
      - port: 15000
        name: http-proxy
        targetPort: 15000
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
    sds:
      enabled: true
      image: node-agent-k8s
  apps-public-ingressgateway:
    type: LoadBalancer
    labels:
      app: apps-public-ingressgateway
      istio: apps-public-ingressgateway
    enabled: true
    ports:
      - port: 80
        targetPort: 80
        name: http2
      - port: 443
        name: https
      - port: 15020
        name: http-status
        targetPort: 15020
      - port: 15000
        name: http-proxy
        targetPort: 15000
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
    sds:
      enabled: true
      image: node-agent-k8s