serviceAccount:
  enabled: true
global:
  controlPlaneSecurityEnabled: false
  mtls:
    # Default setting for service-to-service mtls. Can be set explicitly using
    # destination rules or service annotations.
    enabled: false
  proxy:
    # We on purpose disable auto injections, if false, only explicit annotations
    # turn it on, if true on explict annotations turn it off (and everything gets it)
    # see the table: https://istio.io/help/ops/setup/injection/
    autoInject: disabled
    accessLogFile: "/dev/stdout"
    resources:
      requests:
        cpu: 10m
        memory: 40Mi

  disablePolicyChecks: false

sidecarInjectorWebhook:
  enabled: true
  enableNamespacesByDefault: true
  # If true, webhook or istioctl injector will rewrite PodSpec for liveness
  # health check to redirect request to sidecar. This makes liveness check work
  # even when mTLS is enabled.
  rewriteAppHTTPProbe: false

pilot:
  traceSampling: 100.0
  autoscaleEnabled: false
  resources:
    requests:
      cpu: 500m
      memory: 512Mi

galley:
  enabled: true

mixer:
  policy:
    enabled: true
    autoscaleEnabled: false
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 512Mi

  telemetry:
    enabled: true
    autoscaleEnabled: false
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 512Mi
 
  adapters:
    prometheus:
      enabled: false
      metricsExpiryDuration: 10m
 
grafana:
  enabled: false

tracing:
  enabled: false

kiali:
  enabled: false
  dashboard:
    jaegerURL: http://jaeger-query:16686
    grafanaURL: http://grafana:3000

gateways:
  istio-ingressgateway:
    enabled: false
  sites-public-ingressgateway:
    type: LoadBalancer
    autoscaleEnabled: true
    autoscaleMin: 1
    autoscaleMax: 5
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1024Mi
    cpu:
      targetAverageUtilization: 80
    labels:
      app: sites-public-ingressgateway
      istio: sites-public-ingressgateway
    enabled: true
    ports:
      - port: 80
        targetPort: 80
        name: http2
      - port: 443
        targetPort: 443
        name: https
      - port: 15020
        name: http-status
        targetPort: 15020
      - port: 15000
        name: http-proxy
        targetPort: 15000
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
    sds:
      enabled: true
      image: node-agent-k8s
  sites-private-ingressgateway:
    type: LoadBalancer
    autoscaleEnabled: true
    autoscaleMin: 1
    autoscaleMax: 5
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1024Mi
    cpu:
      targetAverageUtilization: 80
    labels:
      app: sites-private-ingressgateway
      istio: sites-private-ingressgateway
    enabled: true
    ports:
      - port: 80
        targetPort: 80
        name: http2
      - port: 443
        targetPort: 443
        name: https
      - port: 15020
        name: http-status
        targetPort: 15020
      - port: 15000
        name: http-proxy
        targetPort: 15000
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
    sds:
      enabled: true
      image: node-agent-k8s
  apps-private-ingressgateway:
    type: LoadBalancer
    autoscaleEnabled: true
    autoscaleMin: 1
    autoscaleMax: 5
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1024Mi
    cpu:
      targetAverageUtilization: 80
    labels:
      app: apps-private-ingressgateway
      istio: apps-private-ingressgateway
    enabled: true
    ports:
      - port: 80
        name: http2
        targetPort: 80
      - port: 443
        targetPort: 443
        name: https
      - port: 15020
        name: http-status
        targetPort: 15020
      - port: 15000
        name: http-proxy
        targetPort: 15000
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
    sds:
      enabled: true
      image: node-agent-k8s
  apps-public-ingressgateway:
    type: LoadBalancer
    autoscaleEnabled: true
    autoscaleMin: 1
    autoscaleMax: 5
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1024Mi
    cpu:
      targetAverageUtilization: 80
    labels:
      app: apps-public-ingressgateway
      istio: apps-public-ingressgateway
    enabled: true
    ports:
      - port: 80
        targetPort: 80
        name: http2
      - port: 443
        name: https
      - port: 15020
        name: http-status
        targetPort: 15020
      - port: 15000
        name: http-proxy
        targetPort: 15000
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
    sds:
      enabled: true
      image: node-agent-k8s